# Alternative to using postman, solely meant during local development with IntelliJ's http client. For more information visit: https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html
# In contrast to application/json, multipart/form-data requestbodies are very long. For this instance its recommended to generate these form-data-bodies from postman by going to 'Code' "</> Generate Code Snippets" and selecting http

### The only difference compared to the other 2 requests are: username (unique), firstName & lastName
### Register request: John Doe
POST /api/v1/banking/register HTTP/1.1
Host: localhost:8080
Content-Length: 1372
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="oneTimePassword"

OTP-ABC-123-!@#
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

username_1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

password
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="governmentId"; filename="./http_requests_for_intellij_http_client/passport image example.png"
Content-Type: image/png

(data)
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="firstName"

John
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lastName"

Doe
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dateOfBirth"

1970-01-01
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="street"

Banknamestreet
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="houseNumber"

7
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="postalCode"

1234AB
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="city"

Bankcity
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="country"

NL
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Register request: Jane Doe
POST /api/v1/banking/register HTTP/1.1
Host: localhost:8080
Content-Length: 1372
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="oneTimePassword"

OTP-ABC-123-!@#
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

username_2
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

password
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="governmentId"; filename="./http_requests_for_intellij_http_client/passport image example.png"
Content-Type: image/png

(data)
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="firstName"

Jane
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lastName"

Doe
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dateOfBirth"

1970-01-01
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="street"

Banknamestreet
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="houseNumber"

7
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="postalCode"

1234AB
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="city"

Bankcity
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="country"

NL
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Register request: John-Jane Doe II
POST /api/v1/banking/register HTTP/1.1
Host: localhost:8080
Content-Length: 1372
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="oneTimePassword"

OTP-ABC-123-!@#
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

username_3
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

password
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="governmentId"; filename="./http_requests_for_intellij_http_client/passport image example.png"
Content-Type: image/png

(data)
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="firstName"

John-Jane
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lastName"

Doe II
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dateOfBirth"

1970-01-01
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="street"

Banknamestreet
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="houseNumber"

7
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="postalCode"

1234AB
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="city"

Bankcity
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="country"

NL
------WebKitFormBoundary7MA4YWxkTrZu0gW--